version: "3.8"

volumes:
    auctionkuy-mysql-data:
    auctionkuy-minio-data:

services: 

    mysqldb:
        restart: always
        image: mysql
        container_name: mysqldb
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
        environment:
            MYSQL_DATABASE: 'auctionkuy'
            MYSQL_ROOT_PASSWORD: '!auctionkuy123'
        volumes:
          - auctionkuy-mysql-data:/var/lib/mysql
          - ./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql
          - ./mysql/migration.sql:/docker-entrypoint-initdb.d/2.sql
        ports: 
            - "3306:3306"

    redis:
        container_name: auctionkuy-redis
        image: redis:alpine
        command: redis-server --requirepass !auctionkuy123
        restart: always
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
            timeout: 3s
        ports:
            - '6379:6379'
    
    minio:
        restart: always
        image: minio/minio:RELEASE.2021-04-06T23-11-00Z
        container_name: auctionkuy-minio
        command: server /data/minio
        environment:
            MINIO_ROOT_USER: 'auctionkuy'
            MINIO_ROOT_PASSWORD: '!auctionkuy123'
        volumes: 
            - auctionkuy-minio-data:/data
        ports:
            - "9000:9000"

    api:
        container_name: auctionkuy-api
        build: ./api/
        restart: always
        environment: 
            GIN_MODE: 'debug'
            SERVER_HOST : ':8080'
            MAX_PROCESS_NUMBER: '2'
            RATE_LIMIT: '5'
            MYSQL_HOST: 'mysqldb'
            MYSQL_PORT: '3306'
            MYSQL_USERNAME: 'root'
            MYSQL_PASSWORD: '!auctionkuy123'
            MYSQL_DATABASE: 'auctionkuy'
            REDIS_HOST: 'redis'
            REDIS_PASSWORD: '!auctionkuy123'
            REDIS_DB: '0'
            MINIO_ENDPOINT": 'minio:9000'
            MINIO_ACCESS_KEY": 'auctionkuy'
            MINIO_SECRET_KEY: '!auctionkuy123'
            OBJECT_URL_BASE: 'http://localhost:8080/v1'
        ports:
            - '8080:8080'